### ISSUE TITLE
LayoutBuilder as a root widget called twice  causing many issues

### ISSUE THREAD

**Issue by hammadparveez** [beerstorm-net/ulink-url-shortener#1]
I'm using LayoutBuilder for the purpose of Responsive Initialization but Whenever i call setState((){}); in SignUp.dart, What happenes is

MainScreen -> SignUp() runs first then LayoutBuilder -> MaterialApp runs
this is running from bottom to top.[main.dart](https://github.com/hammad143/my_ecom_project_new/blob/main/lib/main.dart)

**Comment by zeusbaba** [comment]
your issue is not related to this repo as it seems.  
Do you need help in fixing your project?

**Comment by hammadparveez** [comment]
Yes i need help in fixing my project. kindly help me please. Sorry for the late reply

**Comment by zeusbaba** [comment]
what kind of help you need?  if you need coding&mentorship then you can find me on codementor.io  
nevertheless, i'll close this issue for it is irrelevant.
